# Generated by Django 4.2.16 on 2026-05-20 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('FLAGGED', 'Flagged')], db_index=True, default='PENDING', max_length=10)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='accounts.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['from_account', 'status'], name='transaction_from_ac_ea5850_idx'), models.Index(fields=['to_account', 'status'], name='transaction_to_acco_e01c03_idx'), models.Index(fields=['from_account', 'timestamp'], name='transaction_from_ac_43b72c_idx'), models.Index(fields=['idempotency_key'], name='transaction_idempot_d892f2_idx')],
            },
        ),
    ]
