# Generated by Django 4.2.16 on 2026-05-20 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('currency', models.CharField(db_index=True, default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='accounts_owner_i_f02236_idx'), models.Index(fields=['owner', 'currency'], name='accounts_owner_i_e8b488_idx')],
            },
        ),
    ]
